name: SkyWarsPro
api: [3.0.0, 4.0.0]
version: 1.0
main: vixikhd\skywars\SkyWars
author: Faizx511x
description: SkyWars minigame plugin
website: https://github.com/GamakCZ/SkyWars

extensions: [mysqli, yaml, json, zip]
softdepend: [EconomyAPI]
depend: [Slapper]

permissions:
  sw.cmd:
    description: Permission to all SkyWars commands
    default: op
    children:
      sw.cmd.help:
        description: Permission for /sw help
        default: op
      sw.cmd.create:
        description: Permission for /sw create
        default: op
      sw.cmd.remove:
        description: Permission for /sw remove
        default: op
      sw.cmd.set:
        description: Permission for /sw set
        default: op
      sw.cmd.arenas:
        description: Permission for /sw arenas
        default: op
      sw.cmd.start:
        description: Permission for /sw start
        default: op
      sw.cmd.test:
        description: Permission for /sw test
        default: op
      sw.cmd.npc:
        description: Permission for /sw npc and /sw npc delete
        default: op
      sw.cmd.shop:
        description: Permission for /sw shop
        default: op
      sw.cmd.kick:
        description: Permission for /sw kick
        default: op
      sw.cmd.leave:
        description: Permission for /sw leave
        default: op
      sw.cmd.join:
        description: Permission for /sw join
        default: op
      sw.cmd.random:
        description: Permission for /sw random
        default: true
      sw.kit:
        description: Permission for all the kits
        default: op
      top.win.skywars:
        description: Permission for Set Leaderboard win text
        default: op
      sw.cmd.version:
        description: Permission for SkyWars version